# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(827, 468)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 70, 781, 211))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(100, 30, 671, 20))
        self.label.setText("")
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 31, 77, 170))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.max = QtWidgets.QPushButton(self.layoutWidget)
        self.max.setDefault(False)
        self.max.setObjectName("max")
        self.verticalLayout.addWidget(self.max)
        self.min = QtWidgets.QPushButton(self.layoutWidget)
        self.min.setObjectName("min")
        self.verticalLayout.addWidget(self.min)
        self.average = QtWidgets.QPushButton(self.layoutWidget)
        self.average.setDefault(False)
        self.average.setObjectName("average")
        self.verticalLayout.addWidget(self.average)
        self.average_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.average_2.setDefault(False)
        self.average_2.setObjectName("average_2")
        self.verticalLayout.addWidget(self.average_2)
        self.avervalue = QtWidgets.QLineEdit(self.groupBox)
        self.avervalue.setGeometry(QtCore.QRect(102, 150, 133, 20))
        self.avervalue.setObjectName("avervalue")
        self.countsvalue = QtWidgets.QLineEdit(self.groupBox)
        self.countsvalue.setGeometry(QtCore.QRect(102, 180, 133, 20))
        self.countsvalue.setObjectName("countsvalue")
        self.maxvalue = QtWidgets.QLineEdit(self.groupBox)
        self.maxvalue.setGeometry(QtCore.QRect(102, 92, 301, 20))
        self.maxvalue.setObjectName("maxvalue")
        self.minvalue = QtWidgets.QLineEdit(self.groupBox)
        self.minvalue.setGeometry(QtCore.QRect(102, 120, 301, 20))
        self.minvalue.setObjectName("minvalue")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 60, 75, 23))
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CalRespondTime"))
        self.groupBox.setTitle(_translate("Form", "选择文件区"))
        self.pushButton.setText(_translate("Form", "选择文件"))
        self.pushButton_2.setText(_translate("Form", "生成折线图"))
        self.max.setText(_translate("Form", "最大值"))
        self.min.setText(_translate("Form", "最小值"))
        self.average.setText(_translate("Form", "平均值"))
        self.average_2.setText(_translate("Form", "计算次数"))
        self.pushButton_3.setText(_translate("Form", "生成柱形图"))
