# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'version.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(419, 208)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 54, 12))
        self.label_2.setObjectName("label_2")
        self.softversion = QtWidgets.QLabel(Dialog)
        self.softversion.setGeometry(QtCore.QRect(110, 30, 171, 16))
        self.softversion.setText("")
        self.softversion.setObjectName("softversion")
        self.builddate = QtWidgets.QLabel(Dialog)
        self.builddate.setGeometry(QtCore.QRect(110, 70, 181, 16))
        self.builddate.setText("")
        self.builddate.setObjectName("builddate")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "版本信息"))
        self.label.setText(_translate("Dialog", "软件版本："))
        self.label_2.setText(_translate("Dialog", "生成日期："))
